#!/usr/bin/env python3
"""Build a justified-gallery layout for the "Us" page.

Reads every photo under assets/img/moment_us/<trip>/, measures its aspect ratio,
and packs each trip's photos into rows that fill the page width edge-to-edge while
keeping every photo's TRUE aspect ratio (no cropping, no stretching) — the classic
Google Photos / Flickr look. Writes _data/moments_layout.yml, consumed by
_includes/moments_gallery.liquid.

Rows whose photos add up to a full width are "flush" (stretched to both edges);
a short trailing row stays "loose" (shown at natural height, centered) so single
or leftover photos are not blown up.

Photos listed in PAIRS are kept together in the same row (e.g. matching his/hers
shots), so they always appear side by side.

Re-run after adding/removing photos:  python3 _scripts/gen_moments_layout.py
"""
import os
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "assets", "img", "moment_us"))
REL_PREFIX = "assets/img/moment_us"
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "_data", "moments_layout.yml"))

TARGET = 3.3      # target sum of aspect ratios per row (~ page_width / row_height)
MIN_FLUSH = 2.5   # rows below this aspect sum are shown loose (not stretched)

# Photos that must stay adjacent in the same row. {folder: [[fileA, fileB], ...]}
PAIRS = {
    "2025beijing": [["724701783071795_.pic_hd.jpg", "724721783071801_.pic_hd.jpg"]],
}


def trip_photos(folder):
    d = os.path.join(ROOT, folder)
    out = []
    for fn in sorted(os.listdir(d)):
        if not fn.lower().endswith((".jpg", ".jpeg", ".png")):
            continue
        with Image.open(os.path.join(d, fn)) as im:
            w, h = im.size
        out.append({"fn": fn, "rel": f"{REL_PREFIX}/{folder}/{fn}", "ar": round(w / h, 4)})
    return out


def build_units(photos, pairs):
    """Group photos into units; a pair becomes one atomic unit kept in one row."""
    partner = {}
    for a, b in pairs:
        partner[a] = b
    units, i = [], 0
    fns = [p["fn"] for p in photos]
    while i < len(photos):
        fn = photos[i]["fn"]
        if fn in partner and i + 1 < len(photos) and photos[i + 1]["fn"] == partner[fn]:
            units.append([photos[i], photos[i + 1]])
            i += 2
        else:
            units.append([photos[i]])
            i += 1
    return units


def pack(units):
    rows, cur, s = [], [], 0.0
    for unit in units:
        cur.extend(unit)
        s += sum(p["ar"] for p in unit)
        if s >= TARGET:
            rows.append(cur)
            cur, s = [], 0.0
    if cur:
        rows.append(cur)
    return rows


def main():
    folders = sorted(f for f in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, f)))
    lines = [
        "# AUTO-GENERATED by _scripts/gen_moments_layout.py — do not edit by hand.",
        "# Justified-gallery rows for the Us page (aspect ratios preserved, no cropping).",
        "# Re-run the script after adding or removing photos.",
        "trips:",
    ]
    total = 0
    for folder in folders:
        photos = trip_photos(folder)
        if not photos:
            continue
        rows = pack(build_units(photos, PAIRS.get(folder, [])))
        lines.append(f'  - folder: "{folder}"')
        lines.append("    rows:")
        for row in rows:
            s = sum(p["ar"] for p in row)
            flush = "true" if s >= MIN_FLUSH else "false"
            lines.append(f"      - flush: {flush}")
            lines.append("        items:")
            for p in row:
                lines.append(f'          - {{ rel: "{p["rel"]}", ar: {p["ar"]} }}')
                total += 1
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}  ({total} photos, {len(folders)} trips)")


if __name__ == "__main__":
    main()
