#!/usr/bin/env python3
"""Build a justified-gallery layout for the "Us" page.

Reads every photo under assets/img/moment_us/<trip>/, measures its aspect ratio,
and packs each trip's photos into rows of at most 3 photos, keeping every photo's
TRUE aspect ratio — no cropping, no stretching. Writes _data/moments_layout.yml,
read by _includes/moments_gallery.liquid.

Rows wide enough are "flush" (stretched to both edges, widths proportional to each
photo's aspect ratio so heights match); short rows (a single photo, or a couple of
tall portraits) stay "loose" (natural height, centered) so nothing is blown up.

Photos in PAIRS stay together in one row (e.g. matching his/hers shots).

Re-run after adding/removing photos:  python3 _scripts/gen_moments_layout.py
"""
import math
import os
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "assets", "img", "moment_us"))
REL_PREFIX = "assets/img/moment_us"
OUT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "_data", "moments_layout.yml"))

MAX_PER_ROW = 3   # keep at most 3 photos per row (4 only if a pair would otherwise split)
MIN_FLUSH = 2.0   # rows with a smaller total aspect ratio are shown loose (not stretched)

# Photos that must stay adjacent in the same row. {folder: [[fileA, fileB], ...]}
PAIRS = {
    "2025beijing": [["724701783071795_.pic_hd.jpg", "724721783071801_.pic_hd.jpg"]],
}


def trip_photos(folder):
    d = os.path.join(ROOT, folder)
    out = []
    for fn in sorted(os.listdir(d)):
        if not fn.lower().endswith((".jpg", ".jpeg", ".png")):
            continue
        with Image.open(os.path.join(d, fn)) as im:
            w, h = im.size
        out.append({"fn": fn, "rel": f"{REL_PREFIX}/{folder}/{fn}", "ar": round(w / h, 4), "paired": False})
    return out


def build_units(photos, pairs):
    """Group photos into units; a pair becomes one atomic unit kept in one row."""
    partner = {a: b for a, b in pairs}
    units, i = [], 0
    while i < len(photos):
        fn = photos[i]["fn"]
        if fn in partner and i + 1 < len(photos) and photos[i + 1]["fn"] == partner[fn]:
            photos[i]["paired"] = photos[i + 1]["paired"] = True
            units.append([photos[i], photos[i + 1]])
            i += 2
        else:
            units.append([photos[i]])
            i += 1
    return units


def pack(units):
    rows, cur, cnt = [], [], 0
    for u in units:
        if cnt > 0 and cnt + len(u) > MAX_PER_ROW:
            rows.append(cur)
            cur, cnt = [], 0
        cur.extend(u)
        cnt += len(u)
    if cur:
        rows.append(cur)
    # avoid a lonely trailing single: turn 3+1 into 2+2, unless that splits a pair (then 4)
    if len(rows) >= 2 and len(rows[-1]) == 1:
        prev = rows[-2]
        if len(prev) >= 2 and not (prev[-1]["paired"] and prev[-2]["paired"]):
            rows[-1].insert(0, prev.pop())
        else:
            prev.extend(rows.pop())
    return rows


def main():
    folders = sorted(f for f in os.listdir(ROOT) if os.path.isdir(os.path.join(ROOT, f)))
    lines = [
        "# AUTO-GENERATED by _scripts/gen_moments_layout.py — do not edit by hand.",
        "# Justified-gallery rows for the Us page (<=3 photos/row, aspect ratios preserved).",
        "# Re-run the script after adding or removing photos.",
        "trips:",
    ]
    total = 0
    for folder in folders:
        photos = trip_photos(folder)
        if not photos:
            continue
        rows = pack(build_units(photos, PAIRS.get(folder, [])))
        lines.append(f'  - folder: "{folder}"')
        lines.append("    rows:")
        for row in rows:
            s = sum(p["ar"] for p in row)
            flush = "true" if (len(row) > 1 and s >= MIN_FLUSH) else "false"
            lines.append(f"      - flush: {flush}")
            lines.append("        items:")
            for p in row:
                lines.append(f'          - {{ rel: "{p["rel"]}", ar: {p["ar"]} }}')
                total += 1
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}  ({total} photos, {len(folders)} trips)")


if __name__ == "__main__":
    main()
